### ISSUE TITLE
how run 

### ISSUE THREAD

**Issue by athrungithub** [sardemff7/wayhouse#1]
runing in x11 or in tty, with sudo wayhouse
in x11: 
(wayhouse:8639): libweston-DEBUG: Failed to create X11 input

in tty: lock tty
with sudo
weston_seat_release_keyboard: Assertion `seat->keyboard_device_count >=0` failed.

**Comment by sardemff7** [comment]
Don’t use `sudo`. Just use `wayhouse` to run it.
For now, you must have logind (or a compatible implementation) installed and running to use the DRM backend. The X11 backend works without it.
